// Generated by purs version 0.12.3
"use strict";
var $foreign = require("./foreign.js");
var Effect = require("../Effect/index.js");
module.exports = {
    "__dirname": $foreign["__dirname"],
    "__filename": $foreign["__filename"],
    unsafeRequire: $foreign.unsafeRequire,
    requireResolve: $foreign.requireResolve
};
