// Generated by purs version 0.12.3
"use strict";
var Control_Applicative = require("../Control.Applicative/index.js");
var Control_Semigroupoid = require("../Control.Semigroupoid/index.js");
var Data_Maybe = require("../Data.Maybe/index.js");
var Data_String_CodeUnits = require("../Data.String.CodeUnits/index.js");
var Prelude = require("../Prelude/index.js");
var Read = function (read) {
    this.read = read;
};
var Zero = function (zero) {
    this.zero = zero;
};
var zeroString = new Zero("");
var zeroBoolean = new Zero(false);
var zero = function (dict) {
    return dict.zero;
};
var readString = new Read(Control_Applicative.pure(Data_Maybe.applicativeMaybe));
var readChar = new Read(Data_String_CodeUnits.charAt(0));
var readBoolean = new Read(function (s) {
    if (s === "true") {
        return Control_Applicative.pure(Data_Maybe.applicativeMaybe)(true);
    };
    if (s === "false") {
        return Control_Applicative.pure(Data_Maybe.applicativeMaybe)(false);
    };
    return Data_Maybe.Nothing.value;
});
var read = function (dict) {
    return dict.read;
};
var readDefault = function (dictRead) {
    return function (dictZero) {
        return function ($3) {
            return Data_Maybe.fromMaybe(zero(dictZero))(read(dictRead)($3));
        };
    };
};
module.exports = {
    Read: Read,
    read: read,
    Zero: Zero,
    zero: zero,
    readDefault: readDefault,
    readString: readString,
    readChar: readChar,
    readBoolean: readBoolean,
    zeroString: zeroString,
    zeroBoolean: zeroBoolean
};
